apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reclaim.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reclaim.labels" . | nindent 4 }}
automountServiceAccountToken: true
