apiVersion: v1
kind: Service
metadata:
  name: {{ include "reclaim.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reclaim.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if ne .Values.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  selector:
    {{- include "reclaim.selectorLabels" . | nindent 4 }}
    reclaim.hspace.io/workload: gateway
  ports:
    - name: gateway
      port: {{ .Values.service.port }}
      targetPort: gateway
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
